# -*- coding: utf-8 -*-
"""road_lane_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w6xv6v5xuQPmMJMMQ5MZnGlC6F9bsi7Q
"""

#ROAD LANE DETECTION

import cv2
import matplotlib.pyplot as plt
import numpy as np


def grey(image):
  #convert to grayscale
    image = np.asarray(image)
    return cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

  #Apply Gaussian Blur --> Reduce noise and smoothen image
def gauss(image):
    return cv2.GaussianBlur(image, (5, 5), 0)

  #outline the strongest gradients in the image --> this is where lines in the image are
def canny(image):
    edges = cv2.Canny(image,50,150)
    return edges

def region(image):
    height, width = image.shape
    #isolate the gradients that correspond to the lane lines
    triangle = np.array([
                       [(100, height), (475, 325), (width, height)]
                       ])
    #create a black image with the same dimensions as original image
    mask = np.zeros_like(image)
    #create a mask (triangle that isolates the region of interest in our image)
    mask = cv2.fillPoly(mask, triangle, 255)
    mask = cv2.bitwise_and(image, mask)
    return mask

# def display_lines(image, lines):
    lines_image = np.zeros_like(image)
    #make sure array isn't empty
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line
            #draw lines on a black image
            cv2.line(lines_image, (x1, y1), (x2, y2), (255, 0, 0), 10)
    return lines_image

# def average(image, lines):
    left = []
    right = []

    if lines is not None:
      for line in lines:
        print(line)
        x1, y1, x2, y2 = line.reshape(4)
        #fit line to points, return slope and y-int
        parameters = np.polyfit((x1, x2), (y1, y2), 1)
        print(parameters)
        slope = parameters[0]
        y_int = parameters[1]
        #lines on the right have positive slope, and lines on the left have neg slope
        if slope < 0:
            left.append((slope, y_int))
        else:
            right.append((slope, y_int))
            
    #takes average among all the columns (column0: slope, column1: y_int)
    right_avg = np.average(right, axis=0)
    left_avg = np.average(left, axis=0)
    #create lines based on averages calculates
    left_line = make_points(image, left_avg)
    right_line = make_points(image, right_avg)
    return np.array([left_line, right_line])
# def display_lines(image, lines):
    lines_image = np.zeros_like(image, dtype=np.uint8)  # Ensure the dtype is uint8
    if lines is not None:
        if len(lines.shape) == 3:  # Check if lines is a multi-dimensional array
            for line in lines:
                x1, y1, x2, y2 = line  # Extract line coordinates
                # Convert coordinates to integers
                x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                # Draw lines on the lines_image
                cv2.line(lines_image, (x1, y1), (x2, y2), (255, 0, 0), 10)
        else:
            x1, y1, x2, y2 = lines  # Extract line coordinates
            # Convert coordinates to integers
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            # Draw a single line on the lines_image
            cv2.line(lines_image, (x1, y1), (x2, y2), (255, 0, 0), 10)
    return lines_image




# def average(image, lines):
    left = []
    right = []

    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]  # Extract line coordinates
            # Fit a line to the points and return slope and y-intercept
            parameters = np.polyfit((x1, x2), (y1, y2), 1)
            slope = parameters[0]
            y_int = parameters[1]
            # Lines on the right have positive slope, and lines on the left have negative slope
            if slope < 0:
                left.append((slope, y_int))
            else:
                right.append((slope, y_int))

    # Check if any lines were detected
    if left and right:
        # Take the average among all the columns (column 0: slope, column 1: y_int)
        right_avg = np.average(right, axis=0)
        left_avg = np.average(left, axis=0)
        # Create lines based on averages calculated
        left_line = make_points(image, left_avg)
        right_line = make_points(image, right_avg)
        return np.array([left_line, right_line])
    else:
        return None  # Return None if no lines were detected

def display_lines(image, lines):
    lines_image = np.zeros_like(image, dtype=np.uint8)  # Ensure the dtype is uint8
    if lines is not None:
        for line in lines:
            if len(line) >= 4:  # Check if there are at least four coordinates
                x1, y1, x2, y2 = line[:4]  # Extract the first four coordinates
                # Convert coordinates to integers
                x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                # Draw lines on the lines_image
                cv2.line(lines_image, (x1, y1), (x2, y2), (255, 0, 0), 10)
    return lines_image




def average(image, lines):
    left = []
    right = []

    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]  # Extract line coordinates
            # Fit a line to the points and return slope and y-intercept
            parameters = np.polyfit((x1, x2), (y1, y2), 1)
            slope = parameters[0]
            y_int = parameters[1]
            # Lines on the right have positive slope, and lines on the left have negative slope
            if slope < 0:
                left.append((x1, y1, x2, y2))  # Store the entire line segment
            else:
                right.append((x1, y1, x2, y2))  # Store the entire line segment

    # Check if any lines were detected
    if left and right:
        return np.array([left, right])
    else:
        return None  # Return None if no lines were detected






def make_points(image, average):
    print(average)
    slope, y_int = average
    y1 = image.shape[0]
    #how long we want our lines to be --> 3/5 the size of the image
    y2 = int(y1 * (3/5))
    #determine algebraically
    x1 = int((y1 - y_int) // slope)
    x2 = int((y2 - y_int) // slope)
    return np.array([x1, y1, x2, y2])



'''##### DETECTING lane lines in image ######'''


cap = cv2.VideoCapture(r'G:\Driver Safety\Driver_Safety\test_video\test.mp4')


while True:
    
    ret, image1 = cap.read()

    if not ret:
        break

    copy = np.copy(image1)
    edges = cv2.Canny(copy, 50, 150)
    isolated = region(edges)

    # Detect lines
    lines = cv2.HoughLinesP(isolated, 2, np.pi/180, 100, np.array([]), minLineLength=30, maxLineGap=5)

    if lines is not None:
        averaged_lines = average(copy, lines)
        black_lines = display_lines(copy, averaged_lines)
        lanes = cv2.addWeighted(copy, 0.8, black_lines, 1, 1)
        cv2.imshow("Lane Detection", lanes)
    else:
        # Handle the case where no lines are detected
        cv2.imshow("Lane Detection", copy)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()